### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by belgianrubs** [sdebruyn/homeassistant-bpost-integration#35]
Hello

Today I received a 403 error. Thought that a restart would maybe fix it, but with no luck. I received this error after restarting: 
![image](https://user-images.githubusercontent.com/80924413/149494687-a45bff3f-061f-4b00-98e5-7e34a61ded98.png)
I don't think this error can be fixed at your side as it seems to be a bPost problem, but maybe you encountered this error too?

**Comment by sdebruyn** [comment]
Same, it's broken for me as well since today.

**Comment by schumi2309** [comment]
pareil pour moi ! meme probleme. si je supprime et que je re-install, il ne veux pas mon adresse email !

**Comment by danito** [comment]
Hi
Same here.
I think the default API key is not valid anymore.
I opened an issue on the My-Bpost-Api which this integration uses: https://github.com/sdebruyn/my-bpost-api/issues/7 
Daniel

**Comment by schumi2309** [comment]
Have you a news for the problem ?

**Comment by elRadix** [comment]
same issue here, it used to work last week


```

This error originated from a custom integration.

Logger: custom_components.bpost.config_flow
Source: custom_components/bpost/config_flow.py:46
Integration: bpost My Mail & Parcel tracking (documentation, issues)
First occurred: 09:33:41 (3 occurrences)
Last logged: 09:39:24

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/bpost/config_flow.py", line 94, in async_step_user
    info = await validate_email(self.hass, user_input)
  File "/config/custom_components/bpost/config_flow.py", line 46, in validate_email
    await bpost_api.async_users_email_login()
  File "/usr/local/lib/python3.9/site-packages/my_bpost_api/bpost_api.py", line 124, in async_users_email_login
    response = await self._async_send_request(
  File "/usr/local/lib/python3.9/site-packages/my_bpost_api/bpost_api.py", line 98, in _async_send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://mbassapi.bpost.be/prod_v2/users/emaillogin')


```

**Comment by belgianrubs** [comment]
For some strange reason it started working again today for me?!

**Comment by belgianrubs** [comment]
Today I received the 403 Message again...

**Comment by schumi2309** [comment]
And it doesn't work today

**Comment by belgianrubs** [comment]
@sdebruyn Do you know what could be possibly be the problem? If I find time somewhere I could also take a look...
